### ISSUE TITLE
Feat/MainPageRouter

### ISSUE THREAD

**Issue by inhyuk15** [cnu-bot/cnubot-admin#7]
## Feature Description
Main페이지의 Sidebar를 통해
분석, 학식관리, 교통관리 페이지로 이동할 수 있고

각 페이지에서 상단바를 통해
설정 페이지로 이동할 수 있다.
ex) 사이드바의 학식관리 -> 1학생회관 -> 날짜수정

## Todo list

- [x] 사이드바에서 분석, 학식관리, 교통관리 페이지 이동
- [x] 분석에서 소식, 학식, 교통 메뉴로 이동
- [x] 학식관리에서 기숙사, 1~4학생회관, 생활과학대학 페이지로 이동
- [ ] 학식관리에서 해당 페이지로 이동 후, 시간표 설정으로 이동
- [ ] 학식관리에서 해당 페이지로 이동 후, 메뉴 설정으로 이동
